const AboutSection = () => {
    return (
        <section className="philosophy-section" id="about">
            <div className="philosophy-container">
                <h2 style="font-size: 56px; margin-bottom: 2rem;">About</h2>
                <div className="prism-line"></div>

                <h3 className="about-headline">
                    Certifications
                </h3>

                <p className="philosophy-subheading">
                    All of the certifications can be validated by entering the link. You can also check skills coverage <a
                        href="#skills">here</a>
                </p>

                <div id="certifications" className="certifications">
                    {/* Certificates will be generated by JavaScript */}
                    <button className="see-more-button" type="button" data-bs-toggle="collapse"
                        data-bs-target="#restOfCertifications" aria-expanded="false" aria-controls="restOfCertifications">
                        See more
                    </button>

                    <div className="philosophy-particles particles" id="particles">
                        {/* Particles will be generated by JavaScript */}
                    </div>
                </div>

                <h3 className="about-headline" style="margin: 160px 0 80px 0;">
                    Experience
                </h3>

                <div className="work-experience">
                    {/* experience card */}
                    <div class="experience">
                        <h3 class="experience-title">Senior Fullstack Developer</h3>
                        <h4>FEB 2025 - DEC 2025</h4>
                        <p class="experience-description">
                            VIER
                        </p>

                        <a href="https://www.vier.ai/en/" class="experience-link" target="_blank">
                            Website
                        </a>

                    </div>
                    {/* experience card */}
                    <div class="experience">
                        <h3 class="experience-title">Senior Software Engineer</h3>
                        <h4>JUN 2022 - SEP 2024</h4>
                        <p class="experience-description">
                            IQVIA
                        </p>

                        <a href="https://www.iqvia.com/" class="experience-link" target="_blank">
                            Website
                        </a>

                    </div>
                    {/* experience card */}
                    <div class="experience">
                        <h3 class="experience-title">Front End Developer</h3>
                        <h4>APR 2020 - JUN 2022</h4>
                        <p class="experience-description">
                            TTMS
                        </p>

                        <a href="https://ttms.pl/en/" class="experience-link" target="_blank">
                            Website
                        </a>

                    </div>
                    {/* experience card */}
                    <div class="experience">
                        <h3 class="experience-title">Full Stack Developer</h3>
                        <h4>JUN 2019 - FEB 2020</h4>
                        <p class="experience-description">
                            OAKnode
                        </p>

                        <a href="https://oaknode.com/" class="experience-link" target="_blank">
                            Website
                        </a>

                    </div>
                    {/* experience card */}
                    <div class="experience">
                        <h3 class="experience-title">Front End Developer</h3>
                        <h4>JAN 2019 - APR 2019</h4>
                        <p class="experience-description">
                            Sealcode
                        </p>

                        <a href="https://www.sealcode.org/" class="experience-link" target="_blank">
                            Website
                        </a>

                    </div>
                    {/* experience card */}
                    <div class="experience">
                        <h3 class="experience-title">Junior JavaScript/React Developer</h3>
                        <h4>DEC 2018 - DEC 2019</h4>
                        <p class="experience-description">
                            Nefeni Sp. z o.o.
                        </p>

                        <a href="https://nefeni.pl/" class="experience-link" target="_blank">
                            Website
                        </a>

                    </div>
                    {/* experience card */}
                    <div class="experience">
                        <h3 class="experience-title">Appium Tester</h3>
                        <h4>OCT 2017 - AUG 2018</h4>
                        <p class="experience-description">
                            Nefeni Sp. z o.o.
                        </p>

                        <a href="https://nefeni.pl/" class="experience-link" target="_blank">
                            Website
                        </a>

                    </div>
                    {/* experience card */}
                    <div class="experience">
                        <h3 class="experience-title">Junior Front End Developer</h3>
                        <h4>DEC 2016 - JUN 2017</h4>
                        <p class="experience-description">
                            Nefeni Sp. z o.o.
                        </p>

                        <a href="https://nefeni.pl/" class="experience-link" target="_blank">
                            Website
                        </a>

                    </div>
                    {/* experience card */}
                </div>
            </div>
        </section>
    );
}

export default AboutSection;